[camera]

extrinsic = [
    [1.0, 0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.0],
    [0.0, 0.0, 0.0, 1.0]
]

fov = 90.0
width = 800
height = 800
super_sampling = 0

[[hittable]]
type = "quadric"
A = [
    [1.1, 0.0, 0.0, 0.0],
    [0.0, 0.6, 0.0, 0.0],
    [0.0, 0.0, 1.0, 1.5],
    [0.0, 0.0, 1.5, 1.89]
]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
k_a = 0.1
k_d = 0.8
k_s = 0.1
sh = 1.0

[[light_source]]
position = [0.0, 0.0, 0.0]
intensity = 1.0
